### PR TITLE
feat: add bpmn diagram, users and system module

### PR DESCRIPTION
**Pull request by spider0061**
added bpmn diagram in transaction details, users and system module.
Screenshot from 2020-06-02 17-09-49
Screenshot from 2020-06-02 17-09-57
Screenshot from 2020-06-02 17-15-36
Minor change to UI - 
Screenshot from 2020-06-02 17-27-30

### CODE REVIEW

**Comment by spider0061** [comment]
The BPMN is just for example. I will update it when api is available.
@adamsaghy-dpc Please have a look

**Comment by adamsaghy-dpc** [comment]
Hi

It looks good. I have checked it out to local, but the users and system module was not working. I have got 404 for both :/

**Comment by adamsaghy-dpc** [comment]
Hi

It looks good, but seems the users and system module is missing. I have got 404...

**Comment by spider0061** [comment]
> Hi
> 
> It looks good, but seems the users and system module is missing. I have got 404...

Sorry, I forgot to add app.module.ts in commit earlier. Also, for now users, roles and permission and audit trails won't open as the API is not available but when we click on system it will display the menu.

**Pull request merged**
