### PR TITLE
feat: group the tast of transaction task list 

### PR DESCRIPTION
**Pull request by spider0061**
grouped the tasks of transaction task list table.
Screenshot from 2020-06-01 15-50-50
Screenshot from 2020-06-01 15-51-00

### CODE REVIEW

**Comment by spider0061** [comment]
@adamsaghy-dpc Please Have a look.

**Comment by adamsaghy-dpc** [comment]
Looks good the functionality :)
For better UX, could you please add an icon (maybe an arrow) which indicated you can click on it and it will expanded?

**Comment by spider0061** [comment]
@adamsaghy-dpc done Please have a look

**Comment by adamsaghy-dpc** [comment]
Looks good :)

**Pull request merged**
